package com.ankur.inventory.domain;

public enum Status {

    SUCCESS, NO_NAME_MATCH, CANNOT_REMOVE_ITEM_DOES_NOT_EXIST, CANNOT_UPDATE_ITEM_DOES_NOT_EXIST, CANNOT_ADD_ITEM_ALREADY_EXISTS, CANNOT_UPDATE_ITEM_INFO;

}
